// <auto-generated />
namespace RecipeStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Categories_working : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categories_working));
        
        string IMigrationMetadata.Id
        {
            get { return "201611270102262_Categories_working"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
